In [3]:
import json

with open("school_codes_list.json", "r") as f:
    school_codes_list = json.load(f)

In [ ]:
import pandas as pd

df = pd.read_csv(
    "../raw_data/ELs.txt",
    sep="\t",
    dtype={"CDS": str}
)

df.columns = df.columns.str.strip()

df.head()

,CDS,COUNTY,DISTRICT,SCHOOL,LC,LANGUAGE,GR_TK,GR_KN,GR_1,GR_2,...,GR_5,GR_6,GR_7,GR_8,GR_9,GR_10,GR_11,GR_12,UNGR,TOTAL_EL
0,01100170112607,Alameda,Alameda County Office of Education,Envision Academy for Arts & Technology,bur,Burmese,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
1,01100170112607,Alameda,Alameda County Office of Education,Envision Academy for Arts & Technology,spa,Spanish; Castilian,0,0,0,0,...,0,0,1,1,3,4,4,6,0,19
2,01100170112607,Alameda,Alameda County Office of Education,Envision Academy for Arts & Technology,ara,Arabic,0,0,0,0,...,0,0,0,0,1,0,1,1,0,3
3,01100170123968,Alameda,Alameda County Office of Education,Community School for Creative Education,mis,Uncoded languages (Other non-English languages),0,0,0,0,...,0,2,1,0,0,0,0,0,0,4
4,01100170123968,Alameda,Alameda County Office of Education,Community School for Creative Education,amh,Amharic,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1

In [2]:
df["CountyCode"] = df["CDS"].str[:2]
df["DistrictCode"] = df["CDS"].str[2:7]
df["SchoolCode"] = df["CDS"].str[7:]

In [4]:
df = df[df["SchoolCode"].isin(school_codes_list)].copy()

In [7]:
school_el_totals = (
    df.groupby("SchoolCode", as_index=False)["TOTAL_EL"]
    .sum()
)

In [8]:
school_el_totals

     SchoolCode  TOTAL_EL
0       0100065        60
1       0100081       239
2       0100198       167
3       0100255       503
4       0100354        42
...         ...       ...
1349    5830013       281
1350    5830047         5
1351    5835202        67
1352    5838305        46
1353    6112619         2

[1354 rows x 2 columns]

In [ ]:
school_el_totals.to_csv('../cleaned_data/EL_data.csv')